services:
  ihm:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - ihm-analytics:/app/analytics-data
    restart: unless-stopped

volumes:
  ihm-analytics:
